language: php
php:
  - "5.4"
services:
  - mysql
before_script:
  # install behat, mink etc
  - composer install --no-interaction --prefer-source # Have to prefer source or hit github rate limit
  - git submodule update --init --recursive           # not really needed but makes sure submodules are there
  #- mkdir application/cache application/logs          # create cache and log dirs
  #- chmod 777 application/cache application/logs      # set permission
script:
  - ./bin/behat --config tests/behat/behat.yml -p=TRAVIS_BRANCH  # run behat
